Source/LoremIpsumWeb/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LoremIpsumWeb.Controllers
{
    public class AjaxController : Controller
    {
        private static string loremIpsumText =
@"Lorem ipsum dolor sit amet, consetetur sadipscing elitr,  sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr,  sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr,  sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis.
At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr,  sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr,  At accusam aliquyam diam diam dolore dolores duo eirmod eos erat, et nonumy sed tempor et et invidunt justo labore Stet clita ea et gubergren, kasd magna no rebum. sanctus sea sed takimata ut vero voluptua. est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr,  sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat. 
Consetetur sadipscing elitr,  sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr,  sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr,  sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.";

        private static int anzahlBuchstaben = loremIpsumText.Count();
        private static int anzahlWoerter = loremIpsumText.
            Split(new[] { " " }, StringSplitOptions.RemoveEmptyEntries)
            .Count();
        private static int anzahlAbsaetze = loremIpsumText
            .Split(new[] { Environment.NewLine }, StringSplitOptions.RemoveEmptyEntries)
            .Count();

        public ActionResult LoremIpsum(string itemtyp, int number)
        {
            string dataToTransmit = "Ungültige Eingabe";

            switch (itemtyp)
            {
                case "Buchstabe":
                    dataToTransmit = GetBuchstabe(number);
                    break;
                case "Wort":
                    dataToTransmit = GetWoerter(number);
                    break;
                case "Absatz":
                    dataToTransmit = GetAbsaetze(number);
                    break;
                default:
                    break;
            }

            return Json(dataToTransmit.Trim());
        }
        private string GetBuchstabe(int number)
        {
            string data = string.Empty;

            while (number > 0)
            {
                if (number >= anzahlBuchstaben)
                {
                    data = string.Format("{0}{1}{2}", data, Environment.NewLine, loremIpsumText);
                    number -= anzahlBuchstaben;
                }
                else
                {
                    data = string.Format("{0}{1}{2}", data, Environment.NewLine, string.Join(string.Empty, loremIpsumText.Take(number)));
                    number -= number;
                }
            }

            return data;
        }
        private string GetWoerter(int number)
        {
            string data = string.Empty;

            while (number > 0)
            {
                if (number >= anzahlWoerter)
                {
                    data = string.Format("{0}{1}{2}", data, Environment.NewLine, loremIpsumText);
                    number -= anzahlWoerter;
                }
                else
                {
                    data = string.Format("{0}{1}{2}", data, Environment.NewLine, 
                        string.Join(" ", 
                            loremIpsumText
                                .Split(new[] { " " }, StringSplitOptions.RemoveEmptyEntries)
                                .Take(number)
                        )); 
                    number -= number;
                }
            }

            return data;
        }
        private string GetAbsaetze(int number)
        {
            string data = string.Empty;

            while (number > 0)
            {
                if (number >= anzahlAbsaetze)
                {
                    data = string.Format("{0}{1}{2}", data, Environment.NewLine, loremIpsumText);
                    number -= anzahlAbsaetze;
                }
                else
                {
                    data = string.Format("{0}{1}{2}",
                        data,
                        Environment.NewLine,
                        string.Join(Environment.NewLine, 
                            loremIpsumText
                                .Split(new[] { Environment.NewLine }, StringSplitOptions.RemoveEmptyEntries)
                                .Take(number))
                        ); 
                    number -= anzahlAbsaetze;
                }
            }

            return data;
        }
    }
}

Source/LoremIpsumWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LoremIpsumWeb.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            StreamReader reader = new StreamReader(Server.MapPath("~/LoremIpsum.txt"));
            ViewBag.LoremIpsumFullText = reader.ReadToEnd();
            return View();
            //return Content("Hallo");
        }

        public ActionResult Canvas()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Formular()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Formular(string name, string email, string nachricht)
        {
            ViewBag.Name = name;
            ViewBag.Email = email;
            ViewBag.Nachricht = nachricht;
            return View("Formularauswertung");
        }

        public ActionResult Ajax()
        {
            return View();
        }

    }
}

Source/LoremIpsumWeb/Views/Home/Ajax.cshtml
@{
    ViewBag.Title = "Ajax Element";
}

@section ScriptHead{

    @if (false)
    {
        <script src="/_Scripts/jquery-2.1.1.js"></script>
    }

    <script>

        $(document).ready(LoadTextBox);

        function LoadTextBox() {
            var numberBox = document.getElementById('numberOfItemsInput');
            if (numberBox.validity.valid) {
                var number = $(numberBox).val();
                var itemtype = $('#itemTypDropDown').val();
                
                @{
                    var url = Url.Action("LoremIpsum", "Ajax");
                }

                $('#loremIpsumTextArea').attr('disabled', true);

                $.ajax('@url', {
                    type: 'POST',
                    data: {
                        itemtyp: itemtype,
                        number: number
                    },
                    success: function (result) {

                        $('#loremIpsumTextArea').removeAttr('disabled');
                        $('#loremIpsumTextArea').val(result);

                    },
                    error: function () {

                        $('#loremIpsumTextArea').val('Es trat ein Fehler während der Verbindung zum Server auf...');

                    }
                });
            }
        }

    </script>

}

<div id="loremIpsumGenerierungBox">
    <span id="loremIpsumGenerierungText">Lorem Ipsum Text generieren mit </span>

    <input type="number" id="numberOfItemsInput" min="1" max="1000" value="100" onchange="LoadTextBox()" />

    <select id="itemTypDropDown" onchange="LoadTextBox()">
        <option value="Buchstabe">Buchstaben</option>
        <option value="Wort" selected>W&ouml;rter</option>
        <option value="Absatz">Abs&auml;tze</option>
    </select>

    <textarea id="loremIpsumTextArea"></textarea>

</div>

Source/LoremIpsumWeb/Views/Home/Canvas.cshtml
@{
    ViewBag.Title = "Canvas Element";
    bool useSinus = true;
}

@section ScriptHead{

    @if (false)
    {
        <script src="/_Scripts/jquery-2.1.1.js"></script>
    }
    @if (useSinus)
    {
        <script src="/_Scripts/SinusCanvas.js"></script>    
        <script>
            function drawChart() {
                var gradVal = $('#winkelSlider').val();
                $('#gradLabel').html(gradVal);
                drawSinusGraph('mainCanvas', gradVal);
            }
            $(document).ready(function () {
                drawChart();
            });
        </script>
    }
    else
    {
        <script src="/_Scripts/LoremIpsumCanvas.js"></script> 
    }
}

<canvas id="mainCanvas" width="960" height="350"></canvas>


@if (useSinus)
{
    <input type="range" min="0" max="360" id="winkelSlider" value="0" oninput="drawChart()" />
    <span><label id="gradLabel">0</label> Grad</span>
}
else
{    
    <input type="button" value="Zeichne etwas" class="RightFloatingButton" onclick="drawOnCanvas('mainCanvas')" />
}

Source/LoremIpsumWeb/Views/Home/Formular.cshtml
@{
    ViewBag.Title = "Formularverarbeitung";
}

@section ScriptHead{

    @if (false)
    {
        <script src="/_Scripts/jquery-2.1.1.js"></script>
    }

    <script>
        $(document).on('submit', '#kontaktForm', function (event) {
            if (!ValidateDocument()) {
                event.preventDefault();
            }
        });

        function ValidateDocument() {
            // if HTML 5 Validation can be used correctly, this Method should ALWAYS return TRUE

            // first, reset all validation
            var isValid = true;
            $('#nameTextBox').css('border-color', '');
            $('#emailTextBox').css('border-color', '');
            $('#nachtichtTextBox').css('border-color', '');


            //if(string) checks fr NULL, Empty and undefined
            if (!$('#nameTextBox').val()) {
                $('#nameTextBox').css('border-color', 'red');
                isValid = false;
            }

            if (!$('#emailTextBox').val() || $('#emailTextBox').val().indexof('@@') <= 0) {
                $('#emailTextBox').css('border-color', 'red');
                isValid = false;
            }

            if (!$('#nachtichtTextBox').val()) {
                $('#nachtichtTextBox').css('border-color', 'red');
                isValid = false;
            }


            return isValid;
        }

    </script>
}


@using(Html.BeginForm("Formular", "Home", FormMethod.Post, new { @class = "FormularBox", id="kontaktForm" }))
{
    <span class="FormularDisplay">Name</span>
    <input class="FormularInput" type="text" id="nameTextBox" placeholder="John Doe" name="Name" required />
        
    <span class="FormularDisplay">Email</span>
    <input class="FormularInput" type="email" id="emailTextBox" placeholder="john.doe@example.com" name="Email" required />
    
    <span class="FormularDisplay">Nachricht</span>
    <textarea class="FormularInput" id="nachtichtTextBox" placeholder="meine Meinung" name="Nachricht" required></textarea>
    
    <input type="submit" title="Absenden" class="RightFloatingButton" />
}

Source/LoremIpsumWeb/Views/Home/Formularauswertung.cshtml
@{
    ViewBag.Title = "Formularverarbeitung";
}

@section ScriptHead{

    @if (false)
    {
        <script src="/_Scripts/jquery-2.1.1.js"></script>
    }

}


@using(Html.BeginForm("Formular", "Home", FormMethod.Post, new { @class = "FormularBox" }))
{
    <span class="FormularDisplay">Name</span>
    <span class="FormularInput">@ViewBag.Name</span>
        
    <span class="FormularDisplay">Email</span>
    <span class="FormularInput">@ViewBag.Email</span>
    
    <span class="FormularDisplay">Nachricht</span>
    <span class="FormularInput">@ViewBag.Nachricht</span>
    
    <span id="formularauswertungshinweis">Vielen Dankt f&uuml;r Ihre Angaben. <br /> Keine Angst betreffend Datenschutz, es wurde nichts gespeichert.</span>
}

Source/LoremIpsumWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Wilkommen";
}

@section ScriptHead{

    @if (false)
    {
        <script src="/_Scripts/jquery-2.1.1.js"></script>
    }
}

Lorem ipsum dolor sit amet, consetetur sadipscing elitr,  sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr,  sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr,  sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis.

Source/LoremIpsumWeb/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="author" content="Silvio Stappung" />
    <title>ITEC Testat Webseite von Silvio Stappung</title>
    <link href="/_Styles/Global.css" rel="stylesheet" />
@*    <link href="/_Styles/Main.css" rel="stylesheet" />*@
    <script src="/_Scripts/jquery-2.1.1.js"></script>
    <script src="/_Scripts/jquery.cookie.js"></script>
    <script src="/_Scripts/Global.js"></script>
    <script>
        $(document).ready(function () {
            var theme = readstyle();
            setstyle(theme);
        });
        
        function SwitchStyle() {
            var theme = readstyle();
            if (theme == 'Professional') {
                theme = 'Alternative';
            }
            else if (theme == 'Alternative') {
                theme = 'Weird';
            }
            else {
                theme = 'Professional';
            }
            setstyle(theme);
        }

    </script>

    @RenderSection("ScriptHead", false)

</head>
<body>

    <header>
        ITEC Testat Webseite

        <span id="styleBox">
            
            <span>Aktueller Style: "<span id="themeName"></span>"</span>

            <img src="/Views/Shared/shuffle.png" alt="Switch Style" id="switchThemeIcon" onclick="SwitchStyle()" />

        </span>
    </header>

    <nav>
        <ul>
            <li><a href="@Url.Action("Index", "Home")">Startseite</a></li>
            <li><a href="@Url.Action("Formular", "Home")">Formularverarbeitung</a></li>
            <li><a href="@Url.Action("Canvas", "Home")">Canvas Element</a></li>
            <li><a href="@Url.Action("Ajax", "Home")">Ajax Element</a></li>
        </ul>
    </nav>

    <section id="bodySection">
        <h1>@ViewBag.Title</h1>
        <hr />

        @RenderBody()

        <span class="FloatingClearRegulation">&nbsp;</span>

    </section>

    <footer>
        <span id="leftFoot">
            <a href="https://github.com/freakinChuck/">Created by Silvio Stappung</a>
        </span>
        <span id="rightFoot">
            Developed with a Screen Resolution of 1280 x 800 and Firefox 32
        </span>
    </footer>

</body>
</html>